//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public decimal id { get; set; }
        public string bcode { get; set; }
        public string description { get; set; }
    }
}
