//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependent
    {
        public int ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> dcode { get; set; }
        public Nullable<int> employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
