//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Payroll_Library
{
    using System;
    
    public partial class EmployeeSummaryReport
    {
        public int ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool benefit_enrolled { get; set; }
        public Nullable<int> Dependents { get; set; }
        public Nullable<int> YearsEmployed { get; set; }
    }
}
